
postgres:
	docker run --name postgres-rp -p 5430:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:12-alpine

createdb:
	docker exec -it postgres-rp createdb --username=root --owner=root simple_bank

dropdb:
	docker exec -it postgres-rp dropdb simple_bank

migrateup:
	migrate -path db/migration -database postgresql://root:secret@localhost:5430/simple_bank?sslmode=disable -verbose up

migratedown:
	migrate -path db/migration -database postgresql://root:secret@localhost:5430/simple_bank?sslmode=disable -verbose down

pullSQLC:
	docker pull kjconroy/sqlc

startupSQLC:
	docker run --rm -v $(pwd):/src -w /src kjconroy/sqlc generate

test:
	go test -v -cover ./...

server:
	go run main.go

mock:
	mockgen -package mockdb -destination db/mock/store.go github.com/rtpa25/go_api_worflow/db/sqlc Store


	



